# Build settings

# plugins:
#   - jekyll-katex

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: jekyll/minima
# plugins:
#   - jekyll-remote-theme

# remote_theme: jonaharagon/jekyll-bootstrap-theme
plugins:
  - jemoji

author:
  name: 'Gedalia Koehler'
  email: 'gyk25@drexel.edu'

bootstrap:
  header_pages:
   - about.md
   - fourier_theorem_page\fourier_theorem.md